#!/bin/bash

if [[ $# < 1 ]]; then
  echo "usage: $0 <message>"
  exit -1
fi


message=$1
echo "message = $message"
# copier env de test
cp -r /home/nerd/Documents/MASTER\ 1/GENIE_LOGICIEL/PROJET/DEV_TURING_GALLERY/backend/turgal/* .
git add .
git commit -m "$message"
git push origin master

git push heroku master

